version: 2

jobs:
  build:
    docker:
      - image: sensirion/embedded-ci:2.1.0
    steps:
      - checkout
      - run:
          name: update common repo
          command: git submodule update --init
      - run: make prepare
      - run: make
      - run: make clean
      - run: make style-check
      - run: make release
      - run:
          name: build stub release drivers
          command: |
              (cd release/sht3x
               make CONFIG_I2C_TYPE=hw_i2c
               make CONFIG_I2C_TYPE=sw_i2c
               make clean)
              (cd release/shtc1
               make CONFIG_I2C_TYPE=hw_i2c
               make CONFIG_I2C_TYPE=sw_i2c
               make clean)
      - run:
          name: build Linux release drivers
          command: |
              (cd release/sht3x
               make CONFIG_I2C_TYPE=hw_i2c hw_i2c_impl_src=hw_i2c/sample-implementations/linux_user_space/sensirion_hw_i2c_implementation.c
               make CONFIG_I2C_TYPE=sw_i2c sw_i2c_impl_src=sw_i2c/sample-implementations/linux_user_space/sensirion_sw_i2c_implementation.c
               make clean)
              (cd release/shtc1
               make CONFIG_I2C_TYPE=hw_i2c hw_i2c_impl_src=hw_i2c/sample-implementations/linux_user_space/sensirion_hw_i2c_implementation.c
               make CONFIG_I2C_TYPE=sw_i2c sw_i2c_impl_src=sw_i2c/sample-implementations/linux_user_space/sensirion_sw_i2c_implementation.c
               make clean)

  deploy:
    docker:
      - image: sensirion/embedded-ci:2.1.0
    steps:
      - checkout
      - run:
          name: update common repo
          command: git submodule update --init
      - run: make release
      - run:
          name: Move zip files to artifact directory
          command: |
            mkdir -p /releases
            mv release/*.zip /releases/
      - persist_to_workspace:
          root: /releases
          paths: .
      - store-artifacts:
          path: /releases

  github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: /releases
      - run:
          name: "Publish Release on GitHub"
          command: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n "Embedded-SHT ${CIRCLE_TAG}" -soft ${CIRCLE_TAG} /releases/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^\d+\.\d+\.\d+$/
      - github-release:
          requires:
            - deploy
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
